# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Set working directory
WORKDIR /app

# Copy source code
COPY . /app

RUN python -c "import tomllib; deps = tomllib.load(open('pyproject.toml', 'rb'))['project']['dependencies']; print('\n'.join(deps))" > requirements.txt

# Install dependencies using pip from the requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENV LOGIN_URL=https://ztuufduvb5.execute-api.ap-northeast-2.amazonaws.com/dev/login
ENV SEARCH_URL=https://ztuufduvb5.execute-api.ap-northeast-2.amazonaws.com/dev/search
ENV API_SECRET_KEY=o1jwKE_vQfgsMJid5kZrKZnKGNOkU2UxytvHYwOWbnQ

# Command
CMD ["python3", "gpters_search_mcp_server.py"]